# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  schedule:
  - cron:  '0 12 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        with:
          path: main
      - name: Checkout stackrox repo
        uses: actions/checkout@v3
        with:
          repository: stackrox/stackrox
          path: stackrox
      - name: Declare commit SHA
        id: vars
        shell: bash
        run: |
          echo "sha=$(cd stackrox && git rev-parse HEAD)" >> $GITHUB_OUTPUT
      - name: Run the build process with Docker
        uses: addnab/docker-run-action@v3
        with:
            image: ghcr.io/janisz/indexer@sha256:8c6edc8d99e4166a6d12a8eb05adbd6018e4d8b0984b747ce8628deed92b0839
            registry: ghcr.io
            run: ./entrypoint.sh
            options: |
              -v ${{ github.workspace }}/main/cache:/shared-index
              -v ${{ github.workspace }}/stackrox:/var/project 
              -e INDEXES_CDN_URL=https://stackrox.github.io/goland-indexes/cache/project
              -e PROJECT_ID=stackrox 
              -e COMMIT_ID=${{ steps.vars.outputs.sha }}
      - name: Setup git user, commit and push
        run: |
          git config --global user.email "${{ vars.RHACS_BOT_GITHUB_EMAIL }}"
          git config --global user.name "${{ vars.RHACS_BOT_GITHUB_USERNAME }}"
          cd main
          git add --all .
          git commit -m "Generate index for https://github.com/stackrox/stackrox/commit/${{ steps.vars.outputs.sha }}"
          git push
